export default {
    prefixURL: "http://localhost:8099/",
    backendURL: "rank_page/backend/",
    frontURL: "rank_page/front/",
    deletePeopleByTrack: "delete_people_by_track",
    getPeopleAll: "get_people_all",
    getPeopleByTrack: "get_people_by_track",
    uploadExcel: "upload_excel",
    getTitleName: "get_title_name?title_id=title_name",
    getVoteNumber: "get_vote_number?vote_id=vote_number",
    setTitleName: "set_title_name",
    setVoteNumber: "set_vote_number",
    setPeopleScore: "set_people_score",
    getTrackAll: "get_track_all",
}
